### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by narobertson42** [m8pple/langproc_2014_cw#4]
1. FUNCTION IMPLEMENTATION
   a) Do we have to pre-include stdio.h and stdlib.h. in our make file? If so how?
   b) Do we have to write the function definitions of the functions from the head or is assumed that ARM will just be able to jump to a location with a putchar, getchar, printf etc.
   c) What is the "argument format" in ARM for the functions?
2. TESTING
   a) Is the test compile expected to run through all files in the folder test or specifically the ones given?
   b) Will the actual tests include the practice tests to ensure our compilers are able to do something?
3. ERRORS
   a) Is an ambiguous error for an incorrect input file sufficient?
4. ARM 
   a) What is the address of the ARM Server?

**Comment by OJFord** [comment]
If you're still up and it helps before a more complete/trusted answer:
1. a) See [the bottom of spec.md](https://github.com/m8pple/langproc_2014_cw/blob/master/spec.md#system-header-files) - the stripped includes are in [test/include](https://github.com/m8pple/langproc_2014_cw/tree/master/test/include).
   b) No, and if you did write your own definition it would clash with the one you included (1a) when linking. Idk what you mean by "just be able to" though? It's assumed that it will be able to - when you tell it to! Maybe [this "Hello World" example](http://community.arm.com/groups/processors/blog/2010/02/11/hello-world-in-assembly) is useful.
   c) [LMGTFY](http://en.wikipedia.org/wiki/Calling_convention#ARM) (Wiki). Also see HelloWorld above.
2. a) If you just do 'everything' then if you add tests you won't have to modify your makefile every time.
3. (obviously I can't answer but if I don't write "3." markdown numbers "4" as "3" -_-)
4. a) It was emailed to us on 26 Feb, I won't post it here since I assume it wasn't in the first place due to it being a public repo. And at any rate, the same email also contains your password. Edit: Oh and if you're offsite you'll need to either be on the VPN or SSH in through one of DoC's shell[1-5] servers if that's what caused problems.

**Comment by narobertson42** [comment]
1. That makes some sense, I suppose my question is what is done in the processor when a function is called. Currently my thinking is that I will write a label called function, and on a function call I would jump to said function and return to the call after execution. When using stdio functions do I jump to a label I have created with a function definition I have written? 
2. Sounds deceptively simple.
4. Thanks, had forgotten about the email!

**Comment by OJFord** [comment]
1. Have a look and see :) - and no, since the whole point of including a library header is that you _don't_ have to implement that stuff yourself.
2. Nothing deceptive - if I say `rm *` then it's going to remove every file 'here' however much new stuff I add.

**Comment by m8pple** [comment]
Pretty much what @OJFord said.

Re 2: (a) - this is more for you to show your testing, so it is on whatever test files you are using. If
you don't add more, then it will just be the existing ones.

2(b) - I will use the known samples, as they have the highest likelihood of working, plus
some unseen samples. It's an in-sample vs out-of-sample testing thing (you'll probably
over-fit on the in-sample examples).

Regarding errors (3), the most important thing is to be correct, so something that says
"Error" on any kind of error is better than something that crashes or generates
incorrect code. Some kind of error message identifying the approximate location
of the problem and what is wrong would be better, but it would make more sense to
spend time getting working code-gen on correct files first.
